
GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/651e11447c9be320c45d8994

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
  "name": "Amazing Person",
  "subscribedToChannel": "Web Dev Simplified"
}

###

DELETE http://localhost:3000/subscribers/651e11447c9be320c45d8994

###

PATCH http://localhost:3000/subscribers/651e15b4855eead2160a3300
Content-Type: application/json

{
  "name": "New Name"
}